name: Secrets workflow

on:
  pull_request:
    branches: ["Main"]

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"

    steps:
      - name: echo environment variables
        run: echo "The value of the key ${{ secrets.SECRET_API_KEY}} for $API_CSPROJ_PATH"
